module.exports = [
  {
    name: 'auth',
    paths: ['/v1/auth'],
    target: process.env.IDENTITY_SERVICE_URL,
    secure: false,
    isMultipart: false,
  },
  {
    name: 'users',
    paths: ['/v1/users'],
    target: process.env.IDENTITY_SERVICE_URL,
    secure: true,
  },
  {
    name: 'products',
    paths: ['/v1/products', '/v1/product/categories'],
    target: process.env.COMBINED_SERVICE_URL,
    secure: true,
  },
  {
    name: 'reviews',
    paths: ['/v1/reviews'],
    target: process.env.REVIEW_SERVICE_URL,
    secure: true,
  },
  {
    name: 'inventory',
    paths: ['/v1/inventory'],
    target: process.env.INVENTORY_SERVICE_URL,
    secure: true,
  },
  {
    name: 'media',
    paths: ['/v1/media'],
    target: process.env.MEDIA_SERVICE_URL,
    secure: true,
    isMultipart: true,
  },
  {
    name: 'auditlogs',
    paths: ['/v1/auditlogs'],
    target: process.env.AUDIT_LOG_SERVICE_URL,
    secure: true,
  },
  {
    name: 'carts',
    paths: ['/v1/carts'],
    target: process.env.CART_SERVICE_URL,
    secure: true,
  },
  {
    name: 'orders',
    paths: ['/v1/orders', '/v1/returns'],
    target: process.env.ORDER_SERVICE_URL,
    secure: true,
  },
  {
    name: 'payments',
    paths: ['/v1/payments'],
    target: process.env.PAYMENT_SERVICE_URL,
    secure: true,
  },
  {
    name: 'shipments',
    paths: ['/v1/shipments'],
    target: process.env.SHIPMENT_SERVICE_URL,
    secure: true,
  },
  {
    name: 'notifications',
    paths: ['/v1/notifications', '/v1/preferences', '/v1/templates'],
    target: process.env.NOTIFICATION_SERVICE_URL,
    secure: true,
  },
  {
    name: 'analytics',
    paths: ['/v1/analytics'],
    target: process.env.ANALYTICS_SERVICE_URL,
    secure: true,
  },
  {
    name: 'promotions',
    paths: ['/v1/promotions'],
    target: process.env.PROMOTION_SERVICE_URL,
    secure: true,
  },
];
