openapi: 3.0.3
info:
  title: eServices API Gateway (bundle)
  version: 1.0.0
  description: Aggregated API for all microservices
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT"

servers:
  - url: http://localhost:8000
    description: Local dev

paths:
  $ref: './services/identity/index.yaml#/paths'

components:
  schemas:
    $ref: './services/identity/index.yaml#/components/schemas'
  responses:
    $ref: './services/identity/index.yaml#/components/responses'
  securitySchemes:
    BearerAuth:
      $ref: './services/identity/index.yaml#/components/securitySchemes/BearerAuth'

security:
  - BearerAuth: []
